version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      cron: "0 8 * * 1-5"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      all-non-major:
        patterns:
          - "*"
        exclude-patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      cron: "0 8 * * 1-5" 