name: Renovate

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3:00 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
