name: Renovate

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3:00 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
      metadata: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_GIT_AUTHOR: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"
          RENOVATE_PLATFORM: "github"
          RENOVATE_AUTODISCOVER: "false"
